[build]
    command         = 'npm run build && npm run export'
    commandOrigin   = 'config'
    functions       = '/opt/build/repo/out_functions'
    publish         = '/opt/build/repo/out_publish'